lib: [
  "_build/install/default/lib/mlsp_lib/META"
  "_build/install/default/lib/mlsp_lib/dune-package"
  "_build/install/default/lib/mlsp_lib/initialize.ml"
  "_build/install/default/lib/mlsp_lib/mlsp_lib.a"
  "_build/install/default/lib/mlsp_lib/mlsp_lib.cma"
  "_build/install/default/lib/mlsp_lib/mlsp_lib.cmi"
  "_build/install/default/lib/mlsp_lib/mlsp_lib.cmt"
  "_build/install/default/lib/mlsp_lib/mlsp_lib.cmx"
  "_build/install/default/lib/mlsp_lib/mlsp_lib.cmxa"
  "_build/install/default/lib/mlsp_lib/mlsp_lib.ml"
  "_build/install/default/lib/mlsp_lib/mlsp_lib__Initialize.cmi"
  "_build/install/default/lib/mlsp_lib/mlsp_lib__Initialize.cmt"
  "_build/install/default/lib/mlsp_lib/mlsp_lib__Initialize.cmx"
  "_build/install/default/lib/mlsp_lib/opam"
]
libexec: [
  "_build/install/default/lib/mlsp_lib/mlsp_lib.cmxs"
]
